### ISSUE TITLE
Copy URL feature fails for svg when viewing items with Tiles preview

### ISSUE THREAD

**Issue by AddumOne** [adobe/helix-sidekick-extension#572]
**Description**
SharePoint offers three different display options. When viewing items using the **Tiles** view, the Copy URL feature fails. Alternatively, If you start with the default **List** view and you select the item before changing the view to **Tiles**, Copy URL works!
In summary, results vary depending on the order of operations. 

**To Reproduce**
Steps to reproduce the failure:
1. In the **adobecom** Sharepoint library, go to Documents > milo > libs > img > mnemonics > svg. 
2. Change the list view option to Tiles to see the svg previews.
3. With Sidekick open and select any svg.
4. Choose a copy option under Copy URL.
5. The screen will show the Please wait... notification and remain stuck.
6. See error:
module.js:1574 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'includes')
    at toWebPath (module.js:1574:35)
    at module.js:1765:82
    at Array.map (<anonymous>)
    at doBulkCopyUrls (module.js:1765:34)
    at sk.addEventListener.once (module.js:1878:17)
    at fireEvent (module.js:1034:10)
    at module.js:2929:25

**Expected behavior**
Copy URL is working consistently when changing the view to Tiles before selecting an item.

**Screenshots**
![image](https://github.com/adobe/helix-sidekick-extension/assets/1825487/5d504fbd-0340-49e5-92b9-60b73734ff83)
![image](https://github.com/adobe/helix-sidekick-extension/assets/1825487/3e50f593-777b-4764-870e-c60d176c4e56)

**Additional context**
I was able to produce the same result for "Compact List" if first the "Tiles" view is selected and failure has already been captured.

**Steps to reproduce:**

1. Change the list view option to Tiles to see the svg previews.
2. Choose an .svg and attempt to copy URL with sidekick. Failure occurs.
3. With the same .svg already selected, change the view to Compact List.
4. Attempt to copy URL with Sidekick... another failure occurs.

**Comment by rofe** [comment]
fixed in new sidekick
