### ISSUE TITLE
[JSON Preview] Integer value breaks the rendering

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-sidekick-extension#8]
In a Google spreadsheet, add a column with an integer value and hit the Preview button: in the JSON Preview, you will see the header rows but no value and JS error in the logs:

```
failed to draw view TypeError: value.startsWith is not a function
    at drawValue (json.js:29:13)
    at json.js:78:7
    at Array.forEach (<anonymous>)
    at json.js:76:22
    at Array.forEach (<anonymous>)
    at drawBody (json.js:74:8)
    at json.js:110:5
    at Array.forEach (<anonymous>)
    at draw (json.js:101:23)
    at showSpecialView (module.js:1094:9)
```

Faulty value is the integer one.

See preview for https://main--bamboohr-website--lamontacrook.hlx3.page/blog-query-index.json

**Comment by rofe** [comment]
This needs to be fixed in https://github.com/adobe/helix-sidekick
